### ISSUE TITLE
Math Calloutのtitle innerを細分してスタイリングしやすくする

### ISSUE THREAD

**Issue by RyotaUshio** [RyotaUshio/obsidian-math#15]

**Comment by RyotaUshio** [comment]
Added CSS class `.math-callout-subtitle`

Sample CSS snippet: 
```css
.callout[data-callout="math"] {
    --callout-color: 238, 15, 149;
    border-left: 5px solid rgb(var(--callout-color));
    border-radius: 0px;
    padding: 0px;
    /* font-family: 'Noto Serif JP'; added */
}

.callout[data-callout="math"]>.callout-title {
    padding: 6px;
    padding-left: 12px;
}

.callout[data-callout="math"]>.callout-title>.callout-icon {
    display: none;
}

.callout[data-callout="math"]>.callout-title>.callout-title-inner {
    font-weight: 500;
    /*500*/
    color: rgb(var(--callout-color));
}

.callout[data-callout="math"]>.callout-content {
    background-color: var(--background-primary);
    padding: 1px 20px 2px 20px;
}

.callout[data-callout="math"].math-callout-en > .callout-title > .callout-title-inner {
    font-style: italic;
}

.callout[data-callout="math"] > .callout-title > .callout-title-inner > .math-callout-subtitle {
    font-weight: 300;
    font-size: 85%;
}

.callout[data-callout="math"].math-callout-en>.callout-content {
    font-style: italic;
}
```
