### ISSUE TITLE
Rendering performance is universally worse when this plugin is installed

### ISSUE THREAD

**Issue by xieve** [RyotaUshio/obsidian-math#252]
I have been experiencing performance issues again lately, and I've tracked it down to this plugin. Here are some comparisons via profiler, where I had this plugin deactivated on the left and activated on the right:

<img src="https://github.com/user-attachments/assets/7151db1f-6d42-49d3-95bf-8e3e2b713d3e" width=300 >
<img src="https://github.com/user-attachments/assets/aec96db1-be3c-4d8e-9ece-0f44aed6cf36" width=300 >

_Typing some inline and display math_

<img src="https://github.com/user-attachments/assets/40cd2931-d380-4d6f-b90b-68f73047a865" width=300 />
<img src="https://github.com/user-attachments/assets/484f93fd-2011-415d-ac95-84249da99497" width=300 />

_Scrolling fast in a PDF (likely the same issue as #249)_

Digging further, this seems to be a CSS issue:

<img src="https://github.com/user-attachments/assets/400d8a76-e858-4c29-9387-771c490cd613" width=605><br>

I found an [article on MDN](https://developer.mozilla.org/en-US/docs/Learn/Performance/CSS) on CSS optimization, maybe that helps. Taking a quick look into the static CSS files, I didn't really see anything that looked obvious. 

(My testing was not very scientific, but I repeated it a bunch of times, so I'm pretty sure to have narrowed it down to this particular plugin. I made sure to leave all of the dependencies enabled.)

**Comment by LynetteCullens** [comment]
Yeah. This started happening in July, and gradually got worse as Obsidian continuously pushed updates. I just turned the entire plugin off and started typing my equation links via HTML and css.

**Comment by makamto** [comment]
> Yeah. This started happening in July, and gradually got worse as Obsidian continuously pushed updates. I just turned the entire plugin off and started typing my equation links via HTML and css.

What about those theorem callout? You can do that via HTML and CSS?

**Comment by l1mey112** [comment]
Still having performance problems (ver 2.2.0, obsidian ver 1.7.7), which is such a shame.

**Comment by LynetteCullens** [comment]
> > Yeah. This started happening in July, and gradually got worse as Obsidian continuously pushed updates. I just turned the entire plugin off and started typing my equation links via HTML and css.
> 
> What about those theorem callout? You can do that via HTML and CSS?

He already gives us the css for the callout formatting here:
https://github.com/RyotaUshio/obsidian-latex-theorem-equation-referencer/tree/978f8dc28459fb8c96bf5b732c0f0fa301e2eeea/styles


I discuss some of my workflow here:
https://github.com/RyotaUshio/obsidian-latex-theorem-equation-referencer/discussions/230

Once I figured out that I only needed MathLinks, I deleted this plugin, and created my own templates. The above is old. My new stuff looks like this (if you can figure out how to navigate the incomplete site): https://publish.obsidian.md/blm-uark-cheg/Glossary/Dimension/Sub_Dimension/Force

Since I switched to using HTML and CSS, I no longer suffer the trials of trying to convert notes made with this plugin into a pdf. 

Here is another explanation thread.
https://github.com/zhaoshenzhai/obsidian-mathlinks/discussions/66#discussioncomment-8947555

**Comment by makamto** [comment]
> > > Yeah. This started happening in July, and gradually got worse as Obsidian continuously pushed updates. I just turned the entire plugin off and started typing my equation links via HTML and css.
> > 
> > 
> > What about those theorem callout? You can do that via HTML and CSS?
> 
> He already gives us the css for the callout formatting here: https://github.com/RyotaUshio/obsidian-latex-theorem-equation-referencer/tree/978f8dc28459fb8c96bf5b732c0f0fa301e2eeea/styles
> 
> I discuss some of my workflow here: [#230](https://github.com/RyotaUshio/obsidian-latex-theorem-equation-referencer/discussions/230)
> 
> Once I figured out that I only needed MathLinks, I deleted this plugin, and created my own templates. The above is old. My new stuff looks like this (if you can figure out how to navigate the incomplete site): https://publish.obsidian.md/blm-uark-cheg/Glossary/Dimension/Sub_Dimension/Force
> 
> Since I switched to using HTML and CSS, I no longer suffer the trials of trying to convert notes made with this plugin into a pdf.
> 
> Here is another explanation thread. [zhaoshenzhai/obsidian-mathlinks#66 (comment)](https://github.com/zhaoshenzhai/obsidian-mathlinks/discussions/66#discussioncomment-8947555)

What a wonderful approach! You are a genius! However, I miss the equation numbering and theorem... How do you implement the numbering though.

**Comment by LynetteCullens** [comment]
> do you implement the numbering though.

with `\tag{}`. That's for displaying though. For referencing, MathLinks alone is enough for equations. For theorem referencing, Obsidian has blockid's for that.

**Comment by l1mey112** [comment]
@LynetteCullens can you show me the CSS you use?

**Comment by l1mey112** [comment]
If anyone needs, here is my CSS.

```css
/* https://raw.githubusercontent.com/RyotaUshio/obsidian-math-booster/1c7b106fcfbddccdcda8451de1c21a094994b686/docs/fig/screenshot.png */

.callout[data-callout*="proof"],
.callout[data-callout*="notation"],
.callout[data-callout*="axiom"],
.callout[data-callout*="definition"],
.callout[data-callout*="lemma"],
.callout[data-callout*="proposition"],
.callout[data-callout*="theorem"],
.callout[data-callout*="corollary"],
.callout[data-callout*="claim"],
.callout[data-callout*="assumption"],
.callout[data-callout*="example"],
.callout[data-callout*="exercise"],
.callout[data-callout*="conjecture"],
.callout[data-callout*="hypothesis"],
.callout[data-callout*="remark"] {
	--callout-color: var(--text-normal);
	background-color: rgb(0, 0, 0, 0);
	border: solid var(--border-width);
	border-radius: var(--size-2-3);
	font-family: CMU Serif, Times, Noto Serif JP;

}

.callout[data-callout*="proof"] .callout-icon,
.callout[data-callout*="notation"] .callout-icon,
.callout[data-callout*="axiom"] .callout-icon,
.callout[data-callout*="definition"] .callout-icon,
.callout[data-callout*="lemma"] .callout-icon,
.callout[data-callout*="proposition"] .callout-icon,
.callout[data-callout*="theorem"] .callout-icon,
.callout[data-callout*="corollary"] .callout-icon,
.callout[data-callout*="claim"] .callout-icon,
.callout[data-callout*="assumption"] .callout-icon,
.callout[data-callout*="example"] .callout-icon,
.callout[data-callout*="exercise"] .callout-icon,
.callout[data-callout*="conjecture"] .callout-icon,
.callout[data-callout*="hypothesis"] .callout-icon,
.callout[data-callout*="remark"] .callout-icon {
	display: none;
}

.callout[data-callout*="proof"] .callout-title-inner::before { content: "Proof ("; font-weight: bolder; }
.callout[data-callout*="proof"] .callout-title-inner::after { content: ")."; font-weight: bolder; }

.callout[data-callout*="definition"] .callout-title-inner::before { content: "Definition ("; font-weight: bolder; }
.callout[data-callout*="definition"] .callout-title-inner::after { content: ")."; font-weight: bolder; }

.callout[data-callout*="axiom"] .callout-title-inner::before { content: "Axiom ("; font-weight: bolder; }
.callout[data-callout*="axiom"] .callout-title-inner::after { content: ").";	font-weight: bolder; }

.callout[data-callout*="lemma"] .callout-title-inner::before { content: "Lemma ("; font-weight: bolder; }
.callout[data-callout*="lemma"] .callout-title-inner::after { content: ").";	font-weight: bolder; }

.callout[data-callout*="proposition"] .callout-title-inner::before { content: "Proposition ("; font-weight: bolder; }
.callout[data-callout*="proposition"] .callout-title-inner::after { content: ").";	font-weight: bolder; }

.callout[data-callout*="theorem"] .callout-title-inner::before { content: "Theorem ("; font-weight: bolder; }
.callout[data-callout*="theorem"] .callout-title-inner::after { content: ").";	font-weight: bolder; }

.callout[data-callout*="corollary"] .callout-title-inner::before { content: "Corollary ("; font-weight: bolder; }
.callout[data-callout*="corollary"] .callout-title-inner::after { content: ").";	font-weight: bolder; }

.callout[data-callout*="claim"] .callout-title-inner::before { content: "Claim ("; font-weight: bolder; }
.callout[data-callout*="claim"] .callout-title-inner::after { content: ").";	font-weight: bolder; }

.callout[data-callout*="assumption"] .callout-title-inner::before { content: "Assumption ("; font-weight: bolder; }
.callout[data-callout*="assumption"] .callout-title-inner::after { content: ").";	font-weight: bolder; }

.callout[data-callout*="assumption"] .callout-title-inner::before { content: "Assumption ("; font-weight: bolder; }
.callout[data-callout*="assumption"] .callout-title-inner::after { content: ").";	font-weight: bolder; }

.callout[data-callout*="conjecture"] .callout-title-inner::before { content: "Conjecture ("; font-weight: bolder; }
.callout[data-callout*="conjecture"] .callout-title-inner::after { content: ").";	font-weight: bolder; }

.callout[data-callout*="hypothesis"] .callout-title-inner::before { content: "Hypothesis ("; font-weight: bolder; }
.callout[data-callout*="hypothesis"] .callout-title-inner::after { content: ").";	font-weight: bolder; }

.callout[data-callout*="proof"] .callout-title-inner,
.callout[data-callout*="notation"] .callout-title-inner,
.callout[data-callout*="axiom"] .callout-title-inner,
.callout[data-callout*="definition"] .callout-title-inner,
.callout[data-callout*="lemma"] .callout-title-inner,
.callout[data-callout*="proposition"] .callout-title-inner,
.callout[data-callout*="theorem"] .callout-title-inner,
.callout[data-callout*="corollary"] .callout-title-inner,
.callout[data-callout*="claim"] .callout-title-inner,
.callout[data-callout*="assumption"] .callout-title-inner,
.callout[data-callout*="example"] .callout-title-inner,
.callout[data-callout*="exercise"] .callout-title-inner,
.callout[data-callout*="conjecture"] .callout-title-inner,
.callout[data-callout*="hypothesis"] .callout-title-inner,
.callout[data-callout*="remark"] .callout-title-inner {
	padding-left: 5px;
	font-family: CMU Serif, Times, Noto Sans JP;
	font-weight: normal;
}

.callout[data-callout*="exercise"] .callout-title-inner,
.callout[data-callout*="example"] .callout-title-inner,
.callout[data-callout*="notation"] .callout-title-inner,
.callout[data-callout*="remark"] .callout-title-inner {
	font-weight: bolder;
}
```
